spring:
  application:
    name: payment
  datasource:
    url: jdbc:h2:tcp://localhost/~/win
    username: sa

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false

token:
  secret: guess_secretguess_secretguess_secretguess_secret